# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  apiemployees:
    container_name: employee_backend
    image: employee_backend
    build:
      context: .
      dockerfile: API.Employees/Dockerfile
    ports:
      - 5000:5000
